### ISSUE TITLE
Error after register new Users

### ISSUE THREAD

**Issue by miri4ever** [RMcGirr83/phpBB-3.1-genders#4]
I got this error if new users register at the site:

[phpBB Debug] PHP Warning: in file [ROOT]/vendor/symfony/event-dispatcher/EventDispatcher.php on line 214: call_user_func() expects parameter 1 to be a valid callback, class 'rmcgirr83/genders/event/listener' does not have a method 'user_gender_profile_validate'

There is no input field while register to put in genders. Is this correct ? If so how this error came up ?

Thanks and yours extensions may some of the best ever.

**Comment by rmcgirr83** [comment]
This line needs to be removed from the listener file.  Not sure how it was missed during validation but it was.

'core.ucp_register_data_after'				=> 'user_gender_profile_validate',
