### ISSUE TITLE
Position

### ISSUE THREAD

**Issue by adjustGirl** [RMcGirr83/phpBB-3.1-genders#5]
Can you maybe do this in the next version so that the gender is at the top when you register?  Right now it's bottom. Thank you.

**Comment by rmcgirr83** [comment]
Disable the extension. Change the name of the styles/prosilver/template/event/ucp_register_profile_fields_after.html in the extension to:

- ucp_register_credentials_before if you want the selection to display before the username
- ucp_register_credentials_after if you want the selection to display after the email address
- ucp_register_options_before if you want the selection to display before the language selection
- ucp_register_profile_fields_before if you want the selection to display before the custom profile fields

Once the name is changed re-enable the extension.

I won't be changing the extension for this

**Comment by adjustGirl** [comment]
Okay thanks.  Now the field is above, but unfortunately also below the time zone.  So twice

**Comment by rmcgirr83** [comment]
You were to replace the file. Disable and remove the originalhtml file.

**Comment by adjustGirl** [comment]
You mean ucp_register_profile_fields_after.html? That's done. it's renamed in ucp_register_credentials_before

**Comment by rmcgirr83** [comment]
Purge the cache

**Comment by adjustGirl** [comment]
Sorry for that .. But everything is done. No success. The same ..

**Comment by rmcgirr83** [comment]
That's impossible

**Comment by adjustGirl** [comment]
Okay, will check that out again, step by step. Thanx so long.

**Comment by adjustGirl** [comment]
I have now deleted all and reinstalled it.  And everything is fine.  🎉 Many thanks for your help.  I now only have to install German.  Have a nice weekend.
